import localFont from "next/font/local";
import type { Metadata } from "next";

import CustomBreadcrumbs from "@root/components/base/Breadcrumbs";
import Navbar from "@root/components/base/Navbar";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />

        <main className="pt-20 px-10">
          <CustomBreadcrumbs />
          {children}
        </main>
      </body>
    </html>
  );
}
